---
- name: add epel repo for extra packages from fedora
  yum: name=epel-release

- name: install nginx
  yum: name=nginx

- name: install python34
  yum: name=python34

- name: install python34-devel
  yum: name=python34-devel

- name: install python-devel
  yum: name=python-devel

- name: install libjpeg-devel
  yum: name=libjpeg-devel

- name: install zlib-devel
  yum: name=zlib-devel

- name: install python34-pip
  yum: name=python34-pip

# - include: postgres.yml

- name: install uwsgi
  yum: name=uwsgi

- name: install uwsgi-plugin-python3
  yum: name=uwsgi-plugin-python3

- name: install uwsgi-logger-file
  yum: name=uwsgi-logger-file

- name: install rabbitmq-server
  yum: name=rabbitmq-server
